import {
  trackOrder,
  rightchevron,
  sizechart,
  notification,
  storeLocator,
  country,
  usaFlag,
  language,
  profile,
  faq,
  chat,
  mail,
  policy,
  rate,
  share,
  shipping,
  terms,
} from '../asset/index';

const TopList = [
  {
    id: '1',
    leftIcon: trackOrder,
    title: 'Track Order',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '2',
    leftIcon: sizechart,
    title: 'Size Chart',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '3',
    leftIcon: notification,
    title: 'Notification',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '4',
    leftIcon: storeLocator,
    title: 'Store Locator',
    rightIcon: rightchevron,
    listType: 'none',
  },
];

const BottomList = [
  {
    id: '1',
    leftIcon: country,
    title: 'Country',
    flag: usaFlag,
    rightTxt: 'USA',
    rightIcon: rightchevron,
    listType: 'countryType',
  },
  {
    id: '2',
    leftIcon: language,
    title: 'Language',
    rightTxt: 'ENG',
    rightIcon: rightchevron,
    listType: 'langType',
  },
  {
    id: '3',
    leftIcon: profile,
    title: 'About Us',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '4',
    leftIcon: faq,
    title: 'FAQ',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '5',
    leftIcon: shipping,
    title: 'Shipping & Returns',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '6',
    leftIcon: chat,
    title: 'Chat With Us',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '7',
    leftIcon: rate,
    title: 'Rate Application',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '8',
    leftIcon: share,
    title: 'Share Application',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '9',
    leftIcon: policy,
    title: 'Privacy Policy',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '10',
    leftIcon: terms,
    title: 'Terms & Conditions',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '11',
    leftIcon: mail,
    title: 'Send Us An Email',
    rightIcon: rightchevron,
    listType: 'none',
  },
  {
    id: '12',
    rightTxt: 'App Version 4.0.6(1)',
    listType: 'footer',
  },
];

export { TopList, BottomList };
